"""init schema

Revision ID: 998b6ce72a60
Revises: 
Create Date: 2025-08-29 16:17:01.207124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '998b6ce72a60'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procedures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ms_drg_code', sa.String(), nullable=False),
    sa.Column('ms_drg_description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedures_id'), 'procedures', ['id'], unique=False)
    op.create_index(op.f('ix_procedures_ms_drg_code'), 'procedures', ['ms_drg_code'], unique=False)
    op.create_table('providers',
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('provider_city', sa.String(), nullable=False),
    sa.Column('provider_state', sa.String(), nullable=False),
    sa.Column('provider_zip_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('provider_id')
    )
    op.create_index(op.f('ix_providers_provider_id'), 'providers', ['provider_id'], unique=False)
    op.create_table('provider_procedures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=False),
    sa.Column('total_discharges', sa.Integer(), nullable=False),
    sa.Column('average_covered_charges', sa.Float(), nullable=False),
    sa.Column('average_total_payments', sa.Float(), nullable=False),
    sa.Column('average_medicare_payments', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.provider_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_procedures_id'), 'provider_procedures', ['id'], unique=False)
    op.create_index(op.f('ix_provider_procedures_procedure_id'), 'provider_procedures', ['procedure_id'], unique=False)
    op.create_index(op.f('ix_provider_procedures_provider_id'), 'provider_procedures', ['provider_id'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.provider_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_id'), 'ratings', ['id'], unique=False)
    op.create_index(op.f('ix_ratings_provider_id'), 'ratings', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ratings_provider_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_provider_procedures_provider_id'), table_name='provider_procedures')
    op.drop_index(op.f('ix_provider_procedures_procedure_id'), table_name='provider_procedures')
    op.drop_index(op.f('ix_provider_procedures_id'), table_name='provider_procedures')
    op.drop_table('provider_procedures')
    op.drop_index(op.f('ix_providers_provider_id'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_procedures_ms_drg_code'), table_name='procedures')
    op.drop_index(op.f('ix_procedures_id'), table_name='procedures')
    op.drop_table('procedures')
    # ### end Alembic commands ###
